### ISSUE TITLE
Data model relations in theory and in practice

### ISSUE THREAD

**Issue by skasberger** [ScholCommLab/fhe-collector#7]
What are the relations in theory:

* DOI 2 URL: 1 : n ?
* URL 2 FB Response: 1 : 1 ?
* FB Response 2 CrossRef Event: 1 : 1 ?

What are the relations in practice:

* DOI 2 URL: 1 : 4 or 1 : n ?
* URL 2 FB Response: 1 : n ?
* FB Response 2 CrossRef Event: n : 1 ?

**Comment by Bubblbu** [comment]
- DOI - URL: `1 : n`
- URL - FB Response: `1 : n`
- FB Response - CrossRef Event: `1 : 1`

1. Each DOI is related to multiple URLs. For now we will be aiming for 2 DOI varations, other optional identifiers (i.e., pubmed, pubmed central), a "internal" URL coming from the publisher (in this case PKP/OJS), and finally another optional URL for OA versions for the DOI (coming from unpaywall).
2. Each URL can have multiple FB respones. Not only in practice (due to errors in the FB URL processing heuristics) but also due to the fact that I would say that these FB responses should be treated as immutable objects for each point in time. I.e., a second query after a week simply represents a new response
3. Each response corresponds to a single CrossRef event that we push (immutable as well)

**Comment by Bubblbu** [comment]
Hello, 

I just realized that the data model file only consists of URLs and Articles/DOIs. I just wanted to point you to this file here that I had started to work on during another phase of the project.

data model in peewee: [orm_model.py](https://github.com/ScholCommLab/fhe-plos/blob/master/code/orm_model.py) - let me know if you have any questions, but I think that it should be rather straighforward to translate the peewee code to whichever ORM you're using

It's basically a few `1:n` relations.

1. Each _Article_ can have multiple _URLs_
2. Each _URL_ can have several _Queries_ as the engagement numbers change over time
3. Each _Query_ can also have several corresponding _GraphObjects_ as the internal Facebook algorithms are not perfect (ideally, we'd obviously want a 1:1 in that case)

Finally, we have a 1:4 relation for each _GraphObject_ as each engagement type (reactions, shares, comments, plugin_comments) will correspond to a seperate _CED Event_.

As agreed, I will be working on the CED event format.
